apiVersion: v1
kind: Service
metadata:
  name: {{ include "kuberecovery.fullname" . }}-webhooks
  labels:
    {{- include "kuberecovery.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 10250
      name: webhooks
      protocol: TCP
      targetPort: webhooks
  selector:
    {{- include "kuberecovery.selectorLabels" . | nindent 4 }}


