# permissions for end users to view recoveryresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kuberecovery
    app.kubernetes.io/managed-by: kustomize
  name: recoveryresource-viewer-role
rules:
- apiGroups:
  - kuberecovery.freepik.com
  resources:
  - recoveryresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberecovery.freepik.com
  resources:
  - recoveryresources/status
  verbs:
  - get
