# permissions for end users to edit recoveryconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kuberecovery
    app.kubernetes.io/managed-by: kustomize
  name: recoveryconfig-editor-role
rules:
- apiGroups:
  - kuberecovery.freepik.com
  resources:
  - recoveryconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberecovery.freepik.com
  resources:
  - recoveryconfigs/status
  verbs:
  - get
