---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - kuberecovery.freepik.com
  resources:
  - recoveryconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberecovery.freepik.com
  resources:
  - recoveryconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - kuberecovery.freepik.com
  resources:
  - recoveryconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kuberecovery.freepik.com
  resources:
  - recoveryresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberecovery.freepik.com
  resources:
  - recoveryresources/finalizers
  verbs:
  - update
- apiGroups:
  - kuberecovery.freepik.com
  resources:
  - recoveryresources/status
  verbs:
  - get
  - patch
  - update
